### ISSUE TITLE
How to scope user by tenant

### ISSUE THREAD

**Issue by ServerJunge** [romegadigital/Multitenancy#11]
Hi,

I really like your package! How can I scope the user by its tenant? 

For Example: A tenant (name und domain: company1) has five user. Each user should only the the users of its associated company1.

So \App\User::get(); 

Should only return the five users for company1.

**Comment by Naoray** [comment]
`Tenant::findByDomain('company1_domain')->users` would do the trick. You could also use the tenant middleware and add the user to the `$deferredModels` property using the `applyTenantScope()` method on the `Multitenancy` class. Then `User::get()` should only return the users for that specific tenant.

**Comment by ServerJunge** [comment]
Thanks for the answer. Tenant::findByDomain works, but what if I want to make it dynamic? Or can you give me an exampe for the applyTenantScope?

**Comment by Naoray** [comment]
I am not 100% sure. Maybe @bradenkeith can say more to this matter. My guess is that you can just add all models which you want to `Multitenancy`-Class `$deferredModel` property by adding them via `applyTenantScope()` in an `ServiceProvider`:

```php
use RomegaDigital\Multitenancy\Multitenancy;

$modelsToScope = [
    \App\User::class,
];

//...

public function boot(Multitenancy $multitenancy)
{
    collect($this->modelsToScope)->each(function ($model) {
        $multitenancy->applyTenantScope($model);
    });
}
```

Does this answer your question?

**Comment by bradenkeith** [comment]
Something like: `Tenant::findByDomain(app('multitenancy')->getCurrentSubDomain())->users` would make it dynamic. We keep `getCurrentSubDomain` public so you can do more dynamic queries within your App using the same methods we use in the package.

**Comment by ServerJunge** [comment]
Thanks for your reply. I will try it when I am back at home.
