### ISSUE TITLE
Problem bigincrements

### ISSUE THREAD

**Issue by amaurysoares** [romegadigital/Multitenancy#12]
Hi! Congrats for this awsome package.

Well, I dont know if this is really and issue or only something weird happening inside my computer, but I  was getting the following error: 

"SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `tenant_user` add constraint `tenant_user_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)"

So I changed inside the users migration from "$table->bigIncrements('id');" to "$table->increments('id');" and it fixed the problem. 

My MySql version: 5.7 
Windows (Laragon)

**Comment by bradenkeith** [comment]
User migration isn’t a file this package provides so sounds like a compatibility issue with the authentication mechanism you’re using. Are you using the Laravel auto scaffolding? If so, what version of Laravel are you using?

**Comment by bradenkeith** [comment]
This seems related to the 5.8 release yesterday, which this package is not updated to support yet. At this time, the update you mention may be necessary. Please confirm for me that you are using 5.8. 

https://github.com/laravel/laravel/pull/4946

**Comment by amaurysoares** [comment]
Yes, its 5.8.

**Comment by bradenkeith** [comment]
@amaurysoares Since this is a breaking change with 5.7, I have tagged v2.0 of this package which now utilizes bigIncrements since Laravel 5.8 is moving that direction. 

Any additional 5.8 bug reports will be added to the 2.0 release.
