### ISSUE TITLE
Tenant Route Model binding not working?

### ISSUE THREAD

**Issue by devonmather** [romegadigital/Multitenancy#18]
Hey All,

I'm trying to dig into this but running into a few issues. I might be missing something as this seems like something that would work out of the box based on the documentation.

Currently, I have a product owned by Tenant 1
http://tenant1.exampledomain.test/products/2

If I then log in as Tenant 2 and navigate to this URL
http://tenant2.exampledomain.test/products/2

Then I can see the contents of that product, although I assume I shouldn't?

Quick run down as per the docs;
- Register RomegaDigital\Multitenancy\MultitenancyServiceProvider::class in config/app.php
- Run php artisan multitenancy:install
- Add HasTenants, HasRoles to User model
- Add BelongsToTenant to Product model
- Add 'tenant.auth' => \RomegaDigital\Multitenancy\Middleware\TenantMiddleware::class to routeMiddleware in app/Http/Kernel.php
- I have then wrapped by routes in the route group as below

```
Route::group(['middleware' => ['tenant.auth']], function () {
	Route::resource('/products', 'ProductController');
});
```

Am I missing something, or does tenant route model binding not work out of the box? My expectation here would be a 403 response to the user.

Thanks for any feedback, and let me know if I can provide more helpful info to debug.

**Comment by bradenkeith** [comment]
Looks like you’re missing the BelongsToTenant trait on your products model.

**Comment by devonmather** [comment]
Thanks for replying to this on the weekend. I can confirm the trait is on the model.

I have echoed out the apply method to see if it was exiting early or anything.

```
public function applyTenantScope(Model $model)
{
    echo 'reached 1, ';
    if (is_null($this->tenant)) {
        $this->deferredModels->push($model);

        return;
    }
    
    echo 'reached 2, ';
    if ($this->tenant->domain === 'admin') {
        return;
    }

    echo 'reached 3, ';
    $model->addGlobalScope('tenant', function (Builder $builder) use ($model) {
        echo 'reached 4, ';
        $builder->where($model->qualifyColumn('tenant_id'), '=', $this->tenant->id);
    });
    echo 'reached 5, ';
}
```

That results in the following output "reached 1, reached 1, reached 2, reached 3, reached 5,"

For some reason the addGlobalScope function is not being invoked?

**Comment by devonmather** [comment]
Is there any reason this function would be skipped? 

```$model->addGlobalScope('tenant', function (Builder $builder) use ($model)```

**Comment by bradenkeith** [comment]
When setup correctly, I can't imagine an instance where that'd be the case. If you are able to provide a repo of your code, I can review it and see where things are going wrong!
