### ISSUE TITLE
Class RomegaDigital\Multitenancy\Middleware\GuestTenantMiddleware does not exist

### ISSUE THREAD

**Issue by arislanhaikal** [romegadigital/Multitenancy#20]
after im following your instruction and i will show product related with tenant. Show error : **Class RomegaDigital\Multitenancy\Middleware\GuestTenantMiddleware does not exist,**
I have included the middleware route group on Kernel.php

I see in romegadigital folder on vendors, just looking at the TenantMiddleware.php middleware, I did not find GuestTenantMiddleware.php

Maybe you haven't updated your latest package version on composer

What happen? can you help me

**Comment by Naoray** [comment]
Hi @arislanhaikal, chances are you installed the version 1 of this package. What does your `composer.json` file look like?

**Comment by arislanhaikal** [comment]
i use "romegadigital/multitenancy": "^2.0"

**Comment by Naoray** [comment]
My bad. Seems like the `GuestTenantMiddleware` is only available in `dev-master`. :man_shrugging: don't know why it wasn't released another version. Will contact the owner!

**Comment by arislanhaikal** [comment]
I solved the above problem with a manual clone from Git and the replace vendors

**Comment by bradenkeith** [comment]
I had a few more things I wanted to work into the next release. That's been done this week and I am pushing a release now.
