### ISSUE TITLE
Relation

### ISSUE THREAD

**Issue by ServerJunge** [romegadigital/Multitenancy#23]
Hi,

I know that I can use the console command to add a new related belongs to model

```
use Illuminate\Database\Eloquent\Model;
use RomegaDigital\Multitenancy\Traits\BelongsToTenant;

class Product extends Model
{
    use BelongsToTenant;

    // ...
}
```

But what about the other way around?

**Comment by Naoray** [comment]
Could you please explain your use case a bit further?

**Comment by bradenkeith** [comment]
Similar to the Nova implementation, you will need to create a Tenant model that extends our Tenant model, then update your config file to look at your local app's tenant model. From there, you can add any additional logic you need.

Check out the Nova package's documentation for an example: https://github.com/romegadigital/MultitenancyNovaTool#define-inverse-relationships
