### ISSUE TITLE
Password resets...

### ISSUE THREAD

**Issue by getschools** [romegadigital/Multitenancy#24]
Howdy,

Thanks so much for making this package, it has helped me out tremendously. I just ran into an issue that I'm not sure how to handle. If a user resets their password from a subdomain, the link they get in their email has the subdomain removed. So when they change their password they get sent to the main domain, which doesn't work for them.

How can I get around that?

**Comment by Naoray** [comment]
I haven't tested it, but you should be able to wrap the `Auth::routes()` call within the `multitenancy.guest` middleware?!

**Comment by getschools** [comment]
Thanks for the idea. I tried it and when I click on the reset link that gets emailed, I ended up with this message:

```
There is no tenant at domain ``.
```

Wondering if I need to go in and change how the password reset links are generated.

**Comment by bradenkeith** [comment]
You will need to update your auth logic to consider the subdomain when redirecting after the password reset.
