### ISSUE TITLE
Migration rollback fails

### ISSUE THREAD

**Issue by kylebarney** [romegadigital/Multitenancy#5]
The `php artisan migrate:rollback` command fails because the foreign key constraint is not removed in the `down` method of the `create_tenants_table.php.stub` file prior to attempting to drop the `tenant_user` table. PR on the way.

**Comment by devonmather** [comment]
Additionally, after running ```php artisan multitenancy:migration products``` the down method doesn't have the required dropForeign method on the table.

**Comment by Naoray** [comment]
Since the migrate:fresh command does almost the same as migrate:rollback,
but is much faster we don't need the drop foreign. I am not 100% sure but I
think Taylor wrote somewhere about dropping the down() method in future
laravel versions.

**Comment by Naoray** [comment]
Ofc if you wish to use the migrate:rollback command you re welcome to make
a PR :)

**Comment by bradenkeith** [comment]
Yes, as Taylor has mentioned in the past, the down method is not recommended - always move your DB forward. We will not be implementing further functionality around this and will eventually follow suit with the framework to back out the `down()` function in the future.
